name: Build & Test

on: [push, pull_request]

env:
  KONG_SOURCE_LOCATION: $$GITHUB_WORKSPACE
  KONG_BUILD_TOOLS_LOCATION: $HOME/kong-build-tools

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-18.04

    steps:
    - name: Set env
      run: |
          echo "::set-env name=KONG_SOURCE_LOCATION::$GITHUB_WORKSPACE"
          echo "::set-env name=KONG_BUILD_TOOLS_LOCATION::$HOME/kong-build-tools"
        
    - name: debug
      run: printenv && echo $KONG_SOURCE_LOCATION

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Build Test Image
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make kong-test-container && popd
